swagger: "2.0"
info:
  title: Tour Cost Manager API
  description: Lists all the APIs of the tour cost management application
  version: 1.0.0
host: api.example.com
basePath: /v1
schemes:
  - https
paths:
  /login:
    post:
      summary: Login to the system
      description: Authenticate a user to the system to use the services
      consumes:
        - application/json
      produces:
        - application/json
      response:
        200:
          description: OK
          schema:
            $ref: '#definitions/User'
        404:
          $ref: '#responses/NotFound'
        401:
          $ref: '#responses/Unauthorized'
# Descriptions of common responses
responses:
  NotFound:
    description: The specified resource was not found
    schema:
      $ref: '#/definitions/Error'
  Unauthorized:
    description: Unauthorized
    schema:
      $ref: '#/definitions/Error'
definitions:
  User:
    type: object
    properties:
      id:
        type: integer
        description: The user ID
        example: 1
      email:
        type: string
        description: The user email
        example: johndoe@gmail.com
      firstName:
        type: string
        description: The user first name
        example: John
      lastName:
        type: string
        description: The user last name
        example: Doe
  Error:
    type: object
    properties:
      code:
        type: string
        description: The error code
        example: "NOT_FOUND"
      source:
        type: string
        description: The source param with which the error is associated
        example: "user_id"
      message:
        type: string
        description: Message that explains the error
        example: User id was not found